anguage: node_js

node_js: stable

cache:
  directories:
    - node_modules
before_install:
  - npm install  --production windows-build-tools
  - npm install  node-gyp
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo g
  - export HEXO_ALGOLIA_INDEXING_KEY=${HEXO_ALGOLIA_INDEXING_KEY}
  - hexo algolia

after_script:
  - mv CNAME ./public
  - mv ./baidu_verify_code-6GKUL6kjh5.html ./public
  - cd ./public
  - git init
  - git config user.name "xiaou66"
  - git config user.email "2630316030@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${token}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/xiaou66/xiaou66.github.io

notifications:
  email:
    - 2630316030@qq.com
  on_success: change
  on_failure: always
