alternate: xiaou
# 是否显示页面加载动画 loading-cat
loader:
  start: true # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画
sidebar:
  # Sidebar Position.
  position: right
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg

widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论

# 页尾全站统计
footer:
  since: 2010
  count: true

# 文章界面统计
post:
  count: true
# bgm
audio:
  - title: 列表1
    list:
      - https://music.163.com/#/playlist?id=2943811283
      - https://music.163.com/#/playlist?id=2297706586
  - title: 列表2
    list:
      - https://music.163.com/#/playlist?id=2031842656

menu:
  home: / || home
  # about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart
  # links: /links/ || magic

# Reward (Donate)
reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    # paypal: /paypal.png

# 图片服务
# image_server: "https://api.ghser.com/random/api.php"
# vendors: 
#   css:
#     katex: https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/katex.min.css
#     fancybox: https://cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.csshttps://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.8.1/css/justifiedGallery.min.css
#   js:
#     pace: https://cdn.bootcdn.net/ajax/libs/pace/1.2.4/pace.min.js
#     pjax: https://cdn.bootcdn.net/ajax/libs/jquery.pjax/2.0.1/jquery.pjax.min.js
#     copy_tex: https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/contrib/copy-tex.min.js
#     anime: https://cdn.bootcdn.net/ajax/libs/animejs/3.2.0/anime.min.js
#     algolia: https://cdn.bootcdn.net/ajax/libs/algoliasearch/4.12.2/algoliasearch-lite.umd.js
#     instantsearch: https://cdn.bootcdn.net/ajax/libs/instantsearch.js/4.39.1/instantsearch.production.min.js
#     quicklink: https://cdn.bootcdn.net/ajax/libs/quicklink/2.2.0/quicklink.umd.min.js
#     chart: https://cdn.bootcdn.net/ajax/libs/frappe-charts/1.5.8/frappe-charts.min.iife.min.js
#     fetch: https://cdn.bootcdn.net/ajax/libs/isomorphic-fetch/3.0.0/fetch-npm-browserify.min.js
#     fancybox: https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js,https://cdn.bootcdn.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js,https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
